name : CICD-Workshop

on: 
  release:
    tags:
      - '*'
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          Username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: 77777s/cicd:v1.0
          
          
      - name: Send submit message to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
        # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: ${{secrets.SLACK_NAME}} \n
                             Matriculation: ${{secrets.MARIC}} \n
                             Email: ${{secrets.EMAIL}} \n
                             Repo: ${{github.repositoryUrl}} \n
                             Image name: ${{secrets.IMAGENAME}} \n
                             Image URL: ${{secrets.IMAGEURL}} \n"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
